# Generated by Django 3.0.3 on 2020-02-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
